### ISSUE TITLE
sometimes getCurrentActivity == null.

### ISSUE THREAD

**Issue by tinybright** [yayaa/TheActivityManager#4]

**Comment by yayaa** [comment]
Yes, if there is no running activity registered into TheActivityManager then it will return null.
What is the issue here? [Please see here](https://github.com/yayaa/TheActivityManager/blob/master/library/app/src/main/java/com/yayandroid/theactivitymanager/TheActivityManager.java#L141)

**Comment by tinybright** [comment]
It return null int onActivityResult after I start ActivityForResult from A to B and finish B.

**Comment by yayaa** [comment]
Yes, you are right. Since onActivityResult would be called before onResume method and onPause of activity B is already called, there will be no visible running activity in TheActivityManager. But since you are in onActivityResult, you actually know which activity you are on.

**Comment by tinybright** [comment]
I don't want to pass context to my util class.

**Comment by tinybright** [comment]
I think you can add a method to get the last available Activity.

**Comment by yayaa** [comment]
Ok, the thing is even if i create a method returns the latestKnownActivity it will return activity B instead of A in your case, because onActivityResult of A is called before onDestroy of B so activity B is still in the manager. 

What i would recommend you to call TheActivityManager.getInstance().onResume(this) in onActivityResult before you do anything with getCurrentActivity, this way it will update the state of activityA as running and will return that instance. (It will call onResume method again if you have some base extension or configure method has called, but it will do no harm because it's a flag setting true)

**Comment by tinybright** [comment]
It's a solution.I think I can override onActivityResult in baseActivity,
